name: CI

on:
  pull_request:

  push:

jobs:
  terraform-plan:
    uses: ./.github/workflows/terraform-plan.yml

  security:
    needs: terraform-plan

    uses: ./.github/workflows/security-scan.yml
