name: Terraform Plan

on:
  workflow_call:

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

      contents: read

    steps:
      - Checkout

      - Configure AWS OIDC

      - Terraform Init

      - Terraform Validate

      - Terraform Plan

      - Upload Artifact
